import { Upload, Sliders, Wand2, Download } from "lucide-react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const STEPS = [
  {
    icon: Upload,
    title: "Upload a photo",
    description:
      "Drag and drop or click to browse. We accept JPEG and PNG files up to 5 MB. A well-lit, clear photo gives the best results.",
  },
  {
    icon: Sliders,
    title: "Pick a theme and room type",
    description:
      "Choose the design style you want (e.g. Scandinavian, Industrial) and the type of room so the AI focuses on the right elements.",
  },
  {
    icon: Wand2,
    title: "Set a style strength and generate",
    description:
      "Style Strength controls how much the AI changes your space — Faithful keeps your layout, Bold fully reimagines it. Hit Generate Design and wait ~30 seconds.",
  },
  {
    icon: Download,
    title: "Download your result",
    description:
      "Once the design appears, use the download button to save the image. You can also regenerate with different settings.",
  },
];

const GALLERY_FAQS = [
  {
    question: "How do designs get added to the gallery?",
    answer:
      "After a design is generated, use the Save to Gallery button on the result to store it. Saved designs appear in the Gallery page sorted newest first.",
  },
  {
    question: "What information is stored with each design?",
    answer:
      "Each saved design stores the generated image along with the design theme and room type used to create it. These are shown as badges on every gallery card.",
  },
  {
    question: "Can I delete a design from the gallery?",
    answer:
      "To request a design removal, open an issue or reach out directly via GitHub.",
  },
];

const FAQS = [
  {
    question: "What file formats are supported?",
    answer:
      "JPEG and PNG files up to 5 MB. Other formats (HEIC, WEBP, GIF) are not currently supported. If your photo is larger than 5 MB, compress it first using a tool like Squoosh.",
  },
  {
    question: "What does Style Strength mean?",
    answer:
      "Style Strength maps to the AI model's guidance scale — a number that controls how closely the output follows the chosen design style versus preserving your existing room. Faithful (low scale) keeps your layout intact; Bold (high scale) lets the AI fully reimagine the space.",
  },
  {
    question: "Why does generation take so long?",
    answer:
      "The design is generated by a ControlNet model running on Replicate's infrastructure. Cold starts and queue times can add 20–60 seconds. Once the model is warm, generation typically takes around 15–20 seconds.",
  },
  {
    question: "How do I get the best results?",
    answer:
      "Use a well-lit photo taken straight-on (not at an extreme angle). Avoid heavy fisheye distortion. The more of the room that's visible, the more the AI has to work with. Start with Balanced strength — it's a good middle ground before going bolder.",
  },
  {
    question: "Can I upload the same photo with different settings?",
    answer:
      "Yes. Upload your photo once, then change the theme, room type, or style strength and hit Generate Design again. The photo stays loaded until you remove it.",
  },
  {
    question: "Are my photos stored anywhere?",
    answer:
      "Photos are sent to Replicate's API for processing and are subject to their data retention policy. They are not stored in this application.",
  },
];

export default function HelpPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">Help</h1>
        <p className="text-muted-foreground mt-1 text-sm">
          Everything you need to get great results from Interior Designer AI.
        </p>
      </div>

      <Separator />

      <Card>
        <CardHeader>
          <CardTitle>Getting Started</CardTitle>
          <CardDescription>
            Four steps to your AI-generated design.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ol className="flex flex-col">
            {STEPS.map((step, index) => {
              const Icon = step.icon;
              const isLast = index === STEPS.length - 1;
              return (
                <li key={step.title} className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="bg-primary text-primary-foreground flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-semibold">
                      {index + 1}
                    </div>
                    {!isLast && <div className="bg-border w-px flex-1" />}
                  </div>
                  <div className={isLast ? "pb-0" : "pb-8"}>
                    <div className="flex items-center gap-2">
                      <Icon className="text-muted-foreground h-4 w-4" />
                      <span className="text-sm font-medium">{step.title}</span>
                    </div>
                    <p className="text-muted-foreground mt-1 text-sm">
                      {step.description}
                    </p>
                  </div>
                </li>
              );
            })}
          </ol>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Frequently Asked Questions</CardTitle>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="w-full">
            {FAQS.map((faq, index) => (
              <AccordionItem key={index} value={`faq-${index}`}>
                <AccordionTrigger className="text-left text-sm font-medium">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground text-sm">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Gallery</CardTitle>
          <CardDescription>
            How saving and managing designs works.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="w-full">
            {GALLERY_FAQS.map((faq, index) => (
              <AccordionItem key={index} value={`gallery-faq-${index}`}>
                <AccordionTrigger className="text-left text-sm font-medium">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground text-sm">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </CardContent>
      </Card>
    </div>
  );
}
